language: node_js
node_js:
  - "node"
dist: trusty
env:
  - ENV="development"
  - DEBUG="*"
  - DB_HOST="localhost"
  - DB_NAME="eshop"
install:
  - npm ci
cache:
  directories:
    - "node_modules"  
scripts:
  - nmp run test
